### PR TITLE
Build with bazel

### PR DESCRIPTION
**Pull request by Yannic**

### CODE REVIEW

**Comment by iflan** [comment]
Thanks for the change! I'm a bit behind in handling pull requests, so give me a bit of time to try this out. When I do take the change, I will be pulling it internally and then re-pushing it back out.

**Comment by Yannic** [comment]
@iflan Any news on this (and #130)?

**Comment by sgammon** [comment]
this would be great

**Comment by iflan** [comment]
Sorry I've been extremely slow on this. I'm actually in the process of handing the project off to a new team, so I'll try using this as an example. Thanks for bugging me about it, though!

**Comment by sgammon** [comment]
hey @iflan, no problem, and i appreciate the response.

**Comment by Yannic** [comment]
Let me close this for now. This is very outdated and will probably no longer work with recent versions of Bazel. I'll send a new one soon.

@iflan What's the status of this project? Have you handed it over to a new team?

**Comment by iflan** [comment]
Yes—they are currently evaluating the state of things to prioritize. @nex3, FYI.

**Pull request closed without merging**
